version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: copil_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=copil
      - POSTGRES_PASSWORD=copil
      - POSTGRES_DB=copil
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: copil_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
