"""add_registration_tx_hash_to_workflow

Revision ID: 35469f6b95f5
Revises: dc862ab9d039
Create Date: 2025-06-30 01:21:53.926248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35469f6b95f5'
down_revision: Union[str, None] = 'dc862ab9d039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('registration_tx_hash', sa.String(), nullable=True, comment='Transaction hash from blockchain registration'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'registration_tx_hash')
    # ### end Alembic commands ###
