"""Add foreign key to user_owned_models

Revision ID: 692e445fbe6f
Revises: 64058b0f534c
Create Date: 2025-06-14 01:46:55.928127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '692e445fbe6f'
down_revision: Union[str, None] = '64058b0f534c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('cost_usd', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('request_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('billing_date', sa.DateTime(timezone=True), server_default=sa.text("date_trunc('day', now())"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_events_cost_usd', 'cost_events', ['cost_usd'], unique=False)
    op.create_index('idx_cost_events_created_at', 'cost_events', ['created_at'], unique=False)
    op.create_index('idx_cost_events_operation', 'cost_events', ['operation'], unique=False)
    op.create_index('idx_cost_events_request_details', 'cost_events', ['request_details'], unique=False, postgresql_using='gin')
    op.create_index('idx_cost_events_service_date', 'cost_events', ['service', 'billing_date'], unique=False)
    op.create_index('idx_cost_events_success', 'cost_events', ['success'], unique=False)
    op.create_index('idx_cost_events_user_service', 'cost_events', ['user_id', 'service'], unique=False)
    op.create_index(op.f('ix_cost_events_billing_date'), 'cost_events', ['billing_date'], unique=False)
    op.create_index(op.f('ix_cost_events_cost_usd'), 'cost_events', ['cost_usd'], unique=False)
    op.create_index(op.f('ix_cost_events_id'), 'cost_events', ['id'], unique=False)
    op.create_index(op.f('ix_cost_events_operation'), 'cost_events', ['operation'], unique=False)
    op.create_index(op.f('ix_cost_events_service'), 'cost_events', ['service'], unique=False)
    op.create_index(op.f('ix_cost_events_success'), 'cost_events', ['success'], unique=False)
    op.create_index(op.f('ix_cost_events_user_id'), 'cost_events', ['user_id'], unique=False)
    op.create_table('security_audit_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_security_audit_created_at', 'security_audit_log', ['created_at'], unique=False)
    op.create_index('idx_security_audit_event_data', 'security_audit_log', ['event_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_security_audit_event_type_time', 'security_audit_log', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_security_audit_ip_address', 'security_audit_log', ['ip_address'], unique=False)
    op.create_index('idx_security_audit_risk_score', 'security_audit_log', ['risk_score'], unique=False)
    op.create_index('idx_security_audit_success', 'security_audit_log', ['success'], unique=False)
    op.create_index('idx_security_audit_user_event', 'security_audit_log', ['user_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_log_event_type'), 'security_audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_log_id'), 'security_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_security_audit_log_ip_address'), 'security_audit_log', ['ip_address'], unique=False)
    op.create_index(op.f('ix_security_audit_log_risk_score'), 'security_audit_log', ['risk_score'], unique=False)
    op.create_index(op.f('ix_security_audit_log_session_id'), 'security_audit_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_security_audit_log_success'), 'security_audit_log', ['success'], unique=False)
    op.create_index(op.f('ix_security_audit_log_user_id'), 'security_audit_log', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('privy_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('sca_address', sa.String(length=42), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('api_usage_daily', sa.Integer(), nullable=False),
    sa.Column('ai_calls_daily', sa.Integer(), nullable=False),
    sa.Column('cost_spent_daily_usd', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('account_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_workflows_created', sa.Integer(), nullable=False),
    sa.Column('total_workflows_executed', sa.Integer(), nullable=False),
    sa.Column('total_volume_usd', sa.String(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_last_active', 'users', ['last_active_at'], unique=False)
    op.create_index('idx_user_privy_id', 'users', ['privy_id'], unique=False)
    op.create_index('idx_user_sca_address', 'users', ['sca_address'], unique=False)
    op.create_index('idx_user_tier', 'users', ['tier'], unique=False)
    op.create_index('idx_user_wallet_address', 'users', ['wallet_address'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_privy_id'), 'users', ['privy_id'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_sca_address'), 'users', ['sca_address'], unique=False)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('sca_address', sa.String(length=42), nullable=False),
    sa.Column('total_value_usd', sa.String(), nullable=False),
    sa.Column('asset_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chain_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('daily_change_usd', sa.String(), nullable=False),
    sa.Column('daily_change_percent', sa.String(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_assets', 'portfolio_snapshots', ['asset_breakdown'], unique=False, postgresql_using='gin')
    op.create_index('idx_portfolio_chains', 'portfolio_snapshots', ['chain_breakdown'], unique=False, postgresql_using='gin')
    op.create_index('idx_portfolio_sca_latest', 'portfolio_snapshots', ['sca_address', 'snapshot_at'], unique=False)
    op.create_index('idx_portfolio_snapshot_at', 'portfolio_snapshots', ['snapshot_at'], unique=False)
    op.create_index('idx_portfolio_total_value', 'portfolio_snapshots', ['total_value_usd'], unique=False)
    op.create_index('idx_portfolio_user_sca', 'portfolio_snapshots', ['user_id', 'sca_address'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_id'), 'portfolio_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_sca_address'), 'portfolio_snapshots', ['sca_address'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_snapshot_at'), 'portfolio_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_table('workflows',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('total_gas_saved_wei', sa.String(), nullable=False),
    sa.Column('total_volume_usd', sa.String(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('current_retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_action_config', 'workflows', ['action_config'], unique=False, postgresql_using='gin')
    op.create_index('idx_workflow_action_type', 'workflows', ['action_type'], unique=False)
    op.create_index('idx_workflow_last_triggered', 'workflows', ['last_triggered_at'], unique=False)
    op.create_index('idx_workflow_next_check', 'workflows', ['next_check_at'], unique=False)
    op.create_index('idx_workflow_state', 'workflows', ['current_state'], unique=False)
    op.create_index('idx_workflow_trigger_config', 'workflows', ['trigger_config'], unique=False, postgresql_using='gin')
    op.create_index('idx_workflow_trigger_type', 'workflows', ['trigger_type'], unique=False)
    op.create_index('idx_workflow_user_active', 'workflows', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_workflows_action_type'), 'workflows', ['action_type'], unique=False)
    op.create_index(op.f('ix_workflows_current_state'), 'workflows', ['current_state'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_next_check_at'), 'workflows', ['next_check_at'], unique=False)
    op.create_index(op.f('ix_workflows_trigger_type'), 'workflows', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('execution_cost_usd', sa.String(), nullable=False),
    sa.Column('gas_used', sa.String(), nullable=False),
    sa.Column('gas_price_gwei', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('is_retry', sa.Boolean(), nullable=False),
    sa.Column('parent_execution_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_action_results', 'workflow_executions', ['action_results'], unique=False, postgresql_using='gin')
    op.create_index('idx_execution_cost', 'workflow_executions', ['execution_cost_usd'], unique=False)
    op.create_index('idx_execution_started_at', 'workflow_executions', ['started_at'], unique=False)
    op.create_index('idx_execution_transaction_hash', 'workflow_executions', ['transaction_hash'], unique=False)
    op.create_index('idx_execution_trigger_data', 'workflow_executions', ['trigger_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_execution_user_status', 'workflow_executions', ['user_id', 'status'], unique=False)
    op.create_index('idx_execution_workflow_id', 'workflow_executions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_id'), 'workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_parent_execution_id'), 'workflow_executions', ['parent_execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_started_at'), 'workflow_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_transaction_hash'), 'workflow_executions', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_workflow_executions_user_id'), 'workflow_executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_user_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_transaction_hash'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_started_at'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_parent_execution_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_index('idx_execution_workflow_id', table_name='workflow_executions')
    op.drop_index('idx_execution_user_status', table_name='workflow_executions')
    op.drop_index('idx_execution_trigger_data', table_name='workflow_executions', postgresql_using='gin')
    op.drop_index('idx_execution_transaction_hash', table_name='workflow_executions')
    op.drop_index('idx_execution_started_at', table_name='workflow_executions')
    op.drop_index('idx_execution_cost', table_name='workflow_executions')
    op.drop_index('idx_execution_action_results', table_name='workflow_executions', postgresql_using='gin')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_trigger_type'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_next_check_at'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_current_state'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_action_type'), table_name='workflows')
    op.drop_index('idx_workflow_user_active', table_name='workflows')
    op.drop_index('idx_workflow_trigger_type', table_name='workflows')
    op.drop_index('idx_workflow_trigger_config', table_name='workflows', postgresql_using='gin')
    op.drop_index('idx_workflow_state', table_name='workflows')
    op.drop_index('idx_workflow_next_check', table_name='workflows')
    op.drop_index('idx_workflow_last_triggered', table_name='workflows')
    op.drop_index('idx_workflow_action_type', table_name='workflows')
    op.drop_index('idx_workflow_action_config', table_name='workflows', postgresql_using='gin')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_portfolio_snapshots_user_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_snapshot_at'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_sca_address'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_id'), table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_user_sca', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_total_value', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_snapshot_at', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_sca_latest', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_chains', table_name='portfolio_snapshots', postgresql_using='gin')
    op.drop_index('idx_portfolio_assets', table_name='portfolio_snapshots', postgresql_using='gin')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_sca_address'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_privy_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_wallet_address', table_name='users')
    op.drop_index('idx_user_tier', table_name='users')
    op.drop_index('idx_user_sca_address', table_name='users')
    op.drop_index('idx_user_privy_id', table_name='users')
    op.drop_index('idx_user_last_active', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_audit_log_user_id'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_success'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_session_id'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_risk_score'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_ip_address'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_id'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_event_type'), table_name='security_audit_log')
    op.drop_index('idx_security_audit_user_event', table_name='security_audit_log')
    op.drop_index('idx_security_audit_success', table_name='security_audit_log')
    op.drop_index('idx_security_audit_risk_score', table_name='security_audit_log')
    op.drop_index('idx_security_audit_ip_address', table_name='security_audit_log')
    op.drop_index('idx_security_audit_event_type_time', table_name='security_audit_log')
    op.drop_index('idx_security_audit_event_data', table_name='security_audit_log', postgresql_using='gin')
    op.drop_index('idx_security_audit_created_at', table_name='security_audit_log')
    op.drop_table('security_audit_log')
    op.drop_index(op.f('ix_cost_events_user_id'), table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_success'), table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_service'), table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_operation'), table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_id'), table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_cost_usd'), table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_billing_date'), table_name='cost_events')
    op.drop_index('idx_cost_events_user_service', table_name='cost_events')
    op.drop_index('idx_cost_events_success', table_name='cost_events')
    op.drop_index('idx_cost_events_service_date', table_name='cost_events')
    op.drop_index('idx_cost_events_request_details', table_name='cost_events', postgresql_using='gin')
    op.drop_index('idx_cost_events_operation', table_name='cost_events')
    op.drop_index('idx_cost_events_created_at', table_name='cost_events')
    op.drop_index('idx_cost_events_cost_usd', table_name='cost_events')
    op.drop_table('cost_events')
    # ### end Alembic commands ###
