"""Add SessionKeyGrant model for session key authorizations

Revision ID: b3b7d8d15f31
Revises: c87e1cd81c76
Create Date: 2025-06-16 16:55:15.630613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3b7d8d15f31'
down_revision: Union[str, None] = 'c87e1cd81c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_key_grants',
    sa.Column('public_address', sa.String(length=42), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('encryption_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_key_permissions', 'session_key_grants', ['permissions'], unique=False, postgresql_using='gin')
    op.create_index('idx_session_key_user_expires', 'session_key_grants', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_session_key_grants_expires_at'), 'session_key_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_session_key_grants_id'), 'session_key_grants', ['id'], unique=False)
    op.create_index(op.f('ix_session_key_grants_public_address'), 'session_key_grants', ['public_address'], unique=True)
    op.create_index(op.f('ix_session_key_grants_user_id'), 'session_key_grants', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('workflows', 'trigger_type',
               existing_type=postgresql.ENUM('GREATER_THAN', 'LESS_THAN', name='triggertype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('workflows', 'upkeep_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               comment='The ID returned by Chainlink Automation registry.',
               existing_nullable=True)
    op.alter_column('workflows', 'commitment_hash',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='keccak256 hash of the off-chain action payload.')
    op.drop_constraint('workflows_commitment_hash_key', 'workflows', type_='unique')
    op.create_index(op.f('ix_workflows_commitment_hash'), 'workflows', ['commitment_hash'], unique=True)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_trigger_type'), 'workflows', ['trigger_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_trigger_type'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_commitment_hash'), table_name='workflows')
    op.create_unique_constraint('workflows_commitment_hash_key', 'workflows', ['commitment_hash'])
    op.alter_column('workflows', 'commitment_hash',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='keccak256 hash of the off-chain action payload.')
    op.alter_column('workflows', 'upkeep_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               comment=None,
               existing_comment='The ID returned by Chainlink Automation registry.',
               existing_nullable=True)
    op.alter_column('workflows', 'trigger_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('GREATER_THAN', 'LESS_THAN', name='triggertype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'is_superuser')
    op.drop_index(op.f('ix_session_key_grants_user_id'), table_name='session_key_grants')
    op.drop_index(op.f('ix_session_key_grants_public_address'), table_name='session_key_grants')
    op.drop_index(op.f('ix_session_key_grants_id'), table_name='session_key_grants')
    op.drop_index(op.f('ix_session_key_grants_expires_at'), table_name='session_key_grants')
    op.drop_index('idx_session_key_user_expires', table_name='session_key_grants')
    op.drop_index('idx_session_key_permissions', table_name='session_key_grants', postgresql_using='gin')
    op.drop_table('session_key_grants')
    # ### end Alembic commands ###
