"""Add node tracking and data to workflow execution

Revision ID: b9a4fc8ac70d
Revises: b3b7d8d15f31
Create Date: 2025-06-16 19:48:50.729040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a4fc8ac70d'
down_revision: Union[str, None] = 'b3b7d8d15f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
