"""Initial models

Revision ID: c87e1cd81c76
Revises: 692e445fbe6f
Create Date: 2025-06-16 01:13:28.829300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c87e1cd81c76'
down_revision: Union[str, None] = '692e445fbe6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('workflows', sa.Column('execution_grant', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflows', sa.Column('upkeep_id', sa.BigInteger(), nullable=True))
    op.add_column('workflows', sa.Column('commitment_hash', sa.String(), nullable=False))
    op.add_column('workflows', sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('workflows', sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('workflows', 'trigger_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('GREATER_THAN', 'LESS_THAN', name='triggertype'),
               existing_nullable=False)
    op.drop_index('ix_workflows_id', table_name='workflows')
    op.drop_index('ix_workflows_trigger_type', table_name='workflows')
    op.create_index(op.f('ix_workflows_upkeep_id'), 'workflows', ['upkeep_id'], unique=True)
    op.create_unique_constraint(None, 'workflows', ['commitment_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='unique')
    op.drop_index(op.f('ix_workflows_upkeep_id'), table_name='workflows')
    op.create_index('ix_workflows_trigger_type', 'workflows', ['trigger_type'], unique=False)
    op.create_index('ix_workflows_id', 'workflows', ['id'], unique=False)
    op.alter_column('workflows', 'trigger_type',
               existing_type=sa.Enum('GREATER_THAN', 'LESS_THAN', name='triggertype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('workflows', 'edges')
    op.drop_column('workflows', 'nodes')
    op.drop_column('workflows', 'commitment_hash')
    op.drop_column('workflows', 'upkeep_id')
    op.drop_column('workflows', 'execution_grant')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
