# backend/app/core/contracts.py
import json
from pathlib import Path
from functools import lru_cache
from web3 import Web3, AsyncWeb3
from web3.contract import Contract, AsyncContract

from app.core.config import settings

# The path to the root of the smart contract project
SMART_CONTRACT_PROJECT_ROOT = Path(__file__).parent.parent.parent / "smart_contracts"

@lru_cache()
def get_contract_abi(contract_name: str) -> dict:
    """
    Reads and returns the ABI for a given contract name from its JSON artifact
    generated by Foundry.
    Uses lru_cache to avoid reading the file multiple times.
    """
    # Foundry's output path convention: out/<contract_file_name>.sol/<contract_name>.json
    # Assuming contract_file_name is the same as contract_name for simplicity.
    artifact_path = SMART_CONTRACT_PROJECT_ROOT / "out" / f"{contract_name}.sol" / f"{contract_name}.json"
    
    if not artifact_path.exists():
        raise FileNotFoundError(f"Contract artifact not found at {artifact_path}. Please compile the contracts with 'forge build'.")
    
    with open(artifact_path, "r") as f:
        artifact = json.load(f)
        if "abi" not in artifact:
            raise KeyError(f"ABI not found in contract artifact: {artifact_path}")
        return artifact["abi"]

async def get_workflow_manager_contract() -> AsyncContract:
    """
    Initializes and returns an async Web3 contract instance for the WorkflowManager.
    """
    abi = get_contract_abi("WorkflowManager")
    
    # Ensure the required settings are available
    if not settings.WEB3_PROVIDER_URI:
        raise ValueError("WEB3_PROVIDER_URI is not set in the environment variables.")
    if not settings.WORKFLOW_MANAGER_CONTRACT_ADDRESS:
        raise ValueError("WORKFLOW_MANAGER_CONTRACT_ADDRESS is not set in the environment variables.")

    # Using an async provider
    w3 = AsyncWeb3(Web3.AsyncHTTPProvider(settings.WEB3_PROVIDER_URI))
    
    # Check if connected
    if not await w3.is_connected():
        raise ConnectionError("Could not connect to the Web3 provider.")

    contract_address = w3.to_checksum_address(settings.WORKFLOW_MANAGER_CONTRACT_ADDRESS)
    
    contract = w3.eth.contract(address=contract_address, abi=abi)
    return contract 